Algoritmo "atvAula3"
// Disciplina   : [Be Academy | Lógica de Programação - Aula 3]
// Professor   : Marcos Monteiro
// Descrição   : algoritmo que solicita e mostra o endereço do usuário.
// Autor(a)    : Pedro Henrique Tomaz Vieira
// Data atual  : 29/04/2022
Var
   endereco : caractere
Inicio
      escreval("Olá! Digite seu endereço: ")
      leia(endereco)
      escreval("Seu endereço é ", endereco)
Fimalgoritmo
